openapi: 3.0.1
info:
  description: |-
    Pipelines represent distinct stages in a workflow, like closing a deal or servicing a support ticket. These endpoints provide access to read and modify pipelines in HubSpot. Pipelines support `deals` and `tickets` object types.

    ## Pipeline ID validation

    When calling endpoints that take pipelineId as a parameter, that ID must correspond to an existing, un-archived pipeline. Otherwise the request will fail with a `404 Not Found` response.
  title: CRM Pipelines
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- name: Pipelines
- name: Pipeline Stages
paths:
  /crm/v3/pipelines/{objectType}:
    get:
      description: Return all pipelines for the object type specified by `{objectType}`.
      operationId: get-/crm/v3/pipelines/{objectType}_getAll
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponsePipeline'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - contacts
        - tickets
      summary: Retrieve all pipelines
      tags:
      - Pipelines
    post:
      description: Create a new pipeline with the provided property values. The entire
        pipeline object, including its unique ID, will be returned in the response.
      operationId: post-/crm/v3/pipelines/{objectType}_create
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PipelineInput'
        required: false
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipeline'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - contacts
        - tickets
      summary: Create a pipeline
      tags:
      - Pipelines
  /crm/v3/pipelines/{objectType}/{pipelineId}:
    delete:
      description: Archive the pipeline identified by `{pipelineId}`.
      operationId: delete-/crm/v3/pipelines/{objectType}/{pipelineId}_archive
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: pipelineId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          content: {}
          description: No content
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - contacts
        - tickets
      summary: Archive a pipeline
      tags:
      - Pipelines
    get:
      description: Return a single pipeline object identified by its unique `{pipelineId}`.
      operationId: get-/crm/v3/pipelines/{objectType}/{pipelineId}_getById
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: pipelineId
        required: true
        schema:
          type: string
        style: simple
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipeline'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - contacts
        - tickets
      summary: Return a pipeline by ID
      tags:
      - Pipelines
    patch:
      description: Perform a partial update of the pipeline identified by `{pipelineId}`.
        The updated pipeline will be returned in the response.
      operationId: patch-/crm/v3/pipelines/{objectType}/{pipelineId}_update
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: pipelineId
        required: true
        schema:
          type: string
        style: simple
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PipelinePatchInput'
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipeline'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - contacts
        - tickets
      summary: Update a pipeline
      tags:
      - Pipelines
    put:
      description: Replace all the properties of an existing pipeline with the values
        provided. This will overwrite any existing pipeline stages. The updated pipeline
        will be returned in the response.
      operationId: put-/crm/v3/pipelines/{objectType}/{pipelineId}_replace
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: pipelineId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PipelineInput'
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipeline'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - contacts
        - tickets
      summary: Replace a pipeline
      tags:
      - Pipelines
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages:
    get:
      description: Return all the stages associated with the pipeline identified by
        `{pipelineId}`.
      operationId: get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_getAll
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: pipelineId
        required: true
        schema:
          type: string
        style: simple
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponsePipelineStage'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - contacts
        - tickets
      summary: Return all stages of a pipeline
      tags:
      - Pipeline Stages
    post:
      description: Create a new stage associated with the pipeline identified by `{pipelineId}`.
        The entire stage object, including its unique ID, will be returned in the
        response.
      operationId: post-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_create
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: pipelineId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PipelineStageInput'
        required: false
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PipelineStage'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - contacts
        - tickets
      summary: Create a pipeline stage
      tags:
      - Pipeline Stages
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}:
    delete:
      description: Archive the pipeline stage identified by `{stageId}` associated
        with the pipeline identified by `{pipelineId}`.
      operationId: delete-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_archive
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: pipelineId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: stageId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          content: {}
          description: No content
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - contacts
        - tickets
      summary: Archive a pipeline stage
      tags:
      - Pipeline Stages
    get:
      description: Return the stage identified by `{stageId}` associated with the
        pipeline identified by `{pipelineId}`.
      operationId: get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_getById
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: pipelineId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: stageId
        required: true
        schema:
          type: string
        style: simple
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PipelineStage'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - contacts
        - tickets
      summary: Return a pipeline stage by ID
      tags:
      - Pipeline Stages
    patch:
      description: Perform a partial update of the pipeline stage identified by `{stageId}`
        associated with the pipeline identified by `{pipelineId}`. Any properties
        not included in this update will keep their existing values. The updated stage
        will be returned in the response.
      operationId: patch-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_update
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: pipelineId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: stageId
        required: true
        schema:
          type: string
        style: simple
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PipelineStagePatchInput'
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PipelineStage'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - contacts
        - tickets
      summary: Update a pipeline stage
      tags:
      - Pipeline Stages
    put:
      description: Replace all the properties of an existing pipeline stage with the
        values provided. The updated stage will be returned in the response.
      operationId: put-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_replace
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: pipelineId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: stageId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PipelineStageInput'
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PipelineStage'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - contacts
        - tickets
      summary: Replace a pipeline stage
      tags:
      - Pipeline Stages
components:
  responses:
    Error:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
      description: An error occurred.
  schemas:
    CollectionResponsePipeline:
      example:
        paging:
          next:
            link: ?after=dfa7a8a%3D%3D
            after: dfa7a8a==
        results:
        - createdAt: 2019-10-30T03:30:17.883Z
          archived: false
          displayOrder: 0
          stages:
          - label: In Progress
            displayOrder: 0
            metadata:
              ticketState: OPEN
            createdAt: 2019-10-30T03:30:17.883Z
            updatedAt: 2019-12-07T16:50:06.678Z
            archived: false
            id: "1234912"
          - label: Done
            displayOrder: 0
            metadata:
              ticketState: CLOSED
            createdAt: 2019-10-30T03:30:17.883Z
            updatedAt: 2019-12-07T16:50:06.678Z
            archived: false
            id: "1234914"
          label: My ticket pipeline
          id: "812723471"
          updatedAt: 2019-12-07T16:50:06.678Z
        - createdAt: 2019-10-30T03:30:17.883Z
          archived: false
          displayOrder: 0
          stages:
          - label: In Progress
            displayOrder: 0
            metadata:
              ticketState: OPEN
            createdAt: 2019-10-30T03:30:17.883Z
            updatedAt: 2019-12-07T16:50:06.678Z
            archived: false
            id: "1234912"
          - label: Done
            displayOrder: 0
            metadata:
              ticketState: CLOSED
            createdAt: 2019-10-30T03:30:17.883Z
            updatedAt: 2019-12-07T16:50:06.678Z
            archived: false
            id: "1234914"
          label: My ticket pipeline
          id: "812723471"
          updatedAt: 2019-12-07T16:50:06.678Z
      properties:
        results:
          items:
            $ref: '#/components/schemas/Pipeline'
          type: array
        paging:
          $ref: '#/components/schemas/Paging'
      required:
      - results
      type: object
    CollectionResponsePipelineStage:
      example:
        paging:
          next:
            link: ?after=dfa7a8a%3D%3D
            after: dfa7a8a==
        results:
        - createdAt: 2019-10-30T03:30:17.883Z
          archived: false
          metadata:
            ticketState: OPEN
          displayOrder: 0
          label: In Progress
          id: "1234912"
          updatedAt: 2019-12-07T16:50:06.678Z
        - createdAt: 2019-10-30T03:30:17.883Z
          archived: false
          metadata:
            ticketState: OPEN
          displayOrder: 0
          label: In Progress
          id: "1234912"
          updatedAt: 2019-12-07T16:50:06.678Z
      properties:
        results:
          items:
            $ref: '#/components/schemas/PipelineStage'
          type: array
        paging:
          $ref: '#/components/schemas/Paging'
      required:
      - results
      type: object
    Error:
      example:
        message: Invalid input (details will vary based on the error)
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category: VALIDATION_ERROR
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
      properties:
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          example: An error occurred
          type: string
        correlationId:
          description: A unique identifier for the request. Include this value with
            any error reports or support tickets
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
          format: uuid
          type: string
        category:
          description: The error category
          type: string
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        errors:
          description: further information about the error
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            invalidPropertyName:
            - propertyValue
            missingScopes:
            - scope1
            - scope2
          type: object
        links:
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation
            about the error or recommended remediation steps
          type: object
      required:
      - category
      - correlationId
      - message
      type: object
    ErrorDetail:
      properties:
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          type: string
        in:
          description: The name of the field or parameter in which the error was found.
          type: string
        code:
          description: The status code associated with the error detail
          type: string
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
          type: object
      required:
      - message
      type: object
    NextPage:
      example:
        link: ?after=dfa7a8a%3D%3D
        after: dfa7a8a==
      properties:
        after:
          type: string
        link:
          type: string
      required:
      - after
      type: object
    Paging:
      example:
        next:
          link: ?after=dfa7a8a%3D%3D
          after: dfa7a8a==
      properties:
        next:
          $ref: '#/components/schemas/NextPage'
      type: object
    Pipeline:
      description: A pipeline definition.
      example:
        createdAt: 2019-10-30T03:30:17.883Z
        archived: false
        displayOrder: 0
        stages:
        - label: In Progress
          displayOrder: 0
          metadata:
            ticketState: OPEN
          createdAt: 2019-10-30T03:30:17.883Z
          updatedAt: 2019-12-07T16:50:06.678Z
          archived: false
          id: "1234912"
        - label: Done
          displayOrder: 0
          metadata:
            ticketState: CLOSED
          createdAt: 2019-10-30T03:30:17.883Z
          updatedAt: 2019-12-07T16:50:06.678Z
          archived: false
          id: "1234914"
        label: My ticket pipeline
        id: "812723471"
        updatedAt: 2019-12-07T16:50:06.678Z
      properties:
        stages:
          description: The stages associated with the pipeline. They can be retrieved
            and updated via the pipeline stages endpoints.
          items:
            $ref: '#/components/schemas/PipelineStage'
          type: array
        createdAt:
          description: The date the pipeline was created. The default pipelines will
            have createdAt = 0.
          format: date-time
          type: string
        archivedAt:
          description: The date the pipeline was archived. `archivedAt` will only
            be present if the pipeline is archived.
          format: date-time
          type: string
        updatedAt:
          description: The date the pipeline was last updated.
          format: date-time
          type: string
        archived:
          description: Whether the pipeline is archived.
          type: boolean
        label:
          description: A unique label used to organize pipelines in HubSpot's UI
          type: string
        displayOrder:
          description: The order for displaying this pipeline. If two pipelines have
            a matching `displayOrder`, they will be sorted alphabetically by label.
          format: int32
          type: integer
        id:
          description: A unique identifier generated by HubSpot that can be used to
            retrieve and update the pipeline.
          type: string
      required:
      - archived
      - createdAt
      - displayOrder
      - id
      - label
      - stages
      - updatedAt
      type: object
    PipelineInput:
      description: An input used to create or replace a pipeline's definition.
      example:
        displayOrder: 0
        stages:
        - label: In Progress
          displayOrder: 0
          metadata:
            ticketState: OPEN
        - label: Done
          displayOrder: 1
          metadata:
            ticketState: CLOSED
        label: My replaced pipeline
      properties:
        stages:
          description: Pipeline stage inputs used to create the new or replacement
            pipeline.
          items:
            $ref: '#/components/schemas/PipelineStageInput'
          type: array
        label:
          description: A unique label used to organize pipelines in HubSpot's UI
          type: string
        displayOrder:
          description: The order for displaying this pipeline. If two pipelines have
            a matching `displayOrder`, they will be sorted alphabetically by label.
          format: int32
          type: integer
      required:
      - displayOrder
      - label
      - stages
      type: object
    PipelinePatchInput:
      description: An input used to update some properties on a pipeline definition.
      example:
        displayOrder: 0
        label: My updated pipeline
      properties:
        label:
          description: A unique label used to organize pipelines in HubSpot's UI
          type: string
        displayOrder:
          description: The order for displaying this pipeline. If two pipelines have
            a matching `displayOrder`, they will be sorted alphabetically by label.
          format: int32
          type: integer
        archived:
          description: Whether the pipeline is archived. This property should only
            be provided when restoring an archived pipeline. If it's provided in any
            other call, the request will fail and a `400 Bad Request` will be returned.
          type: boolean
      type: object
    PipelineStage:
      description: A pipeline stage definition.
      example:
        createdAt: 2019-10-30T03:30:17.883Z
        archived: false
        metadata:
          ticketState: OPEN
        displayOrder: 0
        label: In Progress
        id: "1234912"
        updatedAt: 2019-12-07T16:50:06.678Z
      properties:
        createdAt:
          description: The date the pipeline stage was created. The stages on default
            pipelines will have createdAt = 0.
          format: date-time
          type: string
        archivedAt:
          description: The date the pipeline was archived. `archivedAt` will only
            be present if the pipeline is archived.
          format: date-time
          type: string
        updatedAt:
          description: The date the pipeline stage was last updated.
          format: date-time
          type: string
        archived:
          description: Whether the pipeline is archived.
          type: boolean
        label:
          description: A label used to organize pipeline stages in HubSpot's UI. Each
            pipeline stage's label must be unique within that pipeline.
          type: string
        displayOrder:
          description: The order for displaying this pipeline stage. If two pipeline
            stages have a matching `displayOrder`, they will be sorted alphabetically
            by label.
          format: int32
          type: integer
        metadata:
          additionalProperties:
            type: string
          description: |-
            A JSON object containing properties that are not present on all object pipelines.

            For `deals` pipelines, the `probability` field is required (`{ "probability": 0.5 }`), and represents the likelihood a deal will close. Possible values are between 0.0 and 1.0 in increments of 0.1.

            For `tickets` pipelines, the `ticketState` field is optional (`{ "ticketState": "OPEN" }`), and represents whether the ticket remains open or has been closed by a member of your Support team. Possible values are `OPEN` or `CLOSED`.
          type: object
        id:
          description: A unique identifier generated by HubSpot that can be used to
            retrieve and update the pipeline stage.
          type: string
      required:
      - archived
      - createdAt
      - displayOrder
      - id
      - label
      - metadata
      - updatedAt
      type: object
    PipelineStageInput:
      description: An input used to create or replace a pipeline stage's definition.
      example:
        metadata:
          ticketState: CLOSED
        displayOrder: 1
        label: Done
      properties:
        label:
          description: A label used to organize pipeline stages in HubSpot's UI. Each
            pipeline stage's label must be unique within that pipeline.
          type: string
        displayOrder:
          description: The order for displaying this pipeline stage. If two pipeline
            stages have a matching `displayOrder`, they will be sorted alphabetically
            by label.
          format: int32
          type: integer
        metadata:
          additionalProperties:
            type: string
          description: |-
            A JSON object containing properties that are not present on all object pipelines.

            For `deals` pipelines, the `probability` field is required (`{ "probability": 0.5 }`), and represents the likelihood a deal will close. Possible values are between 0.0 and 1.0 in increments of 0.1.

            For `tickets` pipelines, the `ticketState` field is optional (`{ "ticketState": "OPEN" }`), and represents whether the ticket remains open or has been closed by a member of your Support team. Possible values are `OPEN` or `CLOSED`.
          type: object
      required:
      - displayOrder
      - label
      - metadata
      type: object
    PipelineStagePatchInput:
      description: An input used to update some properties on a pipeline definition.
      example:
        metadata:
          ticketState: CLOSED
        displayOrder: 1
        label: Done
      properties:
        label:
          description: A label used to organize pipeline stages in HubSpot's UI. Each
            pipeline stage's label must be unique within that pipeline.
          type: string
        archived:
          description: Whether the pipeline is archived.
          type: boolean
        displayOrder:
          description: The order for displaying this pipeline stage. If two pipeline
            stages have a matching `displayOrder`, they will be sorted alphabetically
            by label.
          format: int32
          type: integer
        metadata:
          additionalProperties:
            type: string
          description: |-
            A JSON object containing properties that are not present on all object pipelines.

            For `deals` pipelines, the `probability` field is required (`{ "probability": 0.5 }`), and represents the likelihood a deal will close. Possible values are between 0.0 and 1.0 in increments of 0.1.

            For `tickets` pipelines, the `ticketState` field is optional (`{ "ticketState": "OPEN" }`), and represents whether the ticket remains open or has been closed by a member of your Support team. Possible values are `OPEN` or `CLOSED`.
          type: object
      required:
      - metadata
      type: object
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            contacts: Read from and write to my Contacts
            tickets: Read and write tickets
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    hapikey:
      in: query
      name: hapikey
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Python
- Ruby
